#numpy practices

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 

In [2]:
r=[1,432,434,54,2,54,38]

In [3]:
arr = np.array(r)

In [4]:
arr

array([  1, 432, 434,  54,   2,  54,  38])

In [5]:
arr.shape

(7,)

In [6]:
arr = np.array([[1,2],[3,4],[5,6]])

In [7]:
arr.shape

(3, 2)

In [8]:
arr = np.random.randint(100,size=(30))

In [9]:
arr

array([74, 93, 15, 43, 88, 83, 47,  3, 53, 54, 73, 54, 71, 37, 90,  2, 70,
       82, 66, 63, 69, 62, 59, 59, 75, 31, 45, 36, 17, 42])

In [10]:
arr.shape

(30,)

In [12]:
arr.reshape(15,2)

array([[74, 93],
       [15, 43],
       [88, 83],
       [47,  3],
       [53, 54],
       [73, 54],
       [71, 37],
       [90,  2],
       [70, 82],
       [66, 63],
       [69, 62],
       [59, 59],
       [75, 31],
       [45, 36],
       [17, 42]])

In [14]:
arr.reshape(5,6)

array([[74, 93, 15, 43, 88, 83],
       [47,  3, 53, 54, 73, 54],
       [71, 37, 90,  2, 70, 82],
       [66, 63, 69, 62, 59, 59],
       [75, 31, 45, 36, 17, 42]])

In [15]:
arr.reshape(5,3,2)

array([[[74, 93],
        [15, 43],
        [88, 83]],

       [[47,  3],
        [53, 54],
        [73, 54]],

       [[71, 37],
        [90,  2],
        [70, 82]],

       [[66, 63],
        [69, 62],
        [59, 59]],

       [[75, 31],
        [45, 36],
        [17, 42]]])

In [16]:
arr.ndim

1

In [19]:
arr=np.random.randint(100,size=(5,6))

In [20]:
arr

array([[65, 13,  0, 12, 45, 49],
       [75, 85, 51, 38,  8, 76],
       [80, 44, 38, 11, 48,  9],
       [67, 11, 88, 50, 36, 19],
       [54, 52, 30, 18, 47, 22]])

In [23]:
I=list(arr.reshape(10,3))

In [24]:
a=np.array(I)

In [25]:
a

array([[65, 13,  0],
       [12, 45, 49],
       [75, 85, 51],
       [38,  8, 76],
       [80, 44, 38],
       [11, 48,  9],
       [67, 11, 88],
       [50, 36, 19],
       [54, 52, 30],
       [18, 47, 22]])

In [26]:
a.shape

(10, 3)

In [27]:
a[5][1]

48

In [28]:
arr.var()

623.2322222222224

In [29]:
arr.min()

0

In [30]:
arr.mean()

41.36666666666667

In [32]:
arr.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [33]:
a.dtype

dtype('int32')